baseURL = ""
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
paginate = 10

theme = "congo"

[taxonomies]
  tag = "tags"
  category = "categories"
  linea = "lineas"

[outputs]
  home = ["HTML", "RSS", "JSON"]
