[es]
  languageCode = "es"
  weight = 1
  languageName = "Español"
  title = "Jose Agudelo"

  [es.params]
    description = "Filósofo, humanista digital, data scientist."

    [es.params.author]
      name = "Jose Agudelo Londoño"
      bio = "Humanista digital. Con formación en filosofía, experiencia en comunicación e iniciando en ciencia de datos."
      headline = "Humanista digital. Con formación en filosofía, experiencia en comunicación e iniciando en ciencia de datos."
      image = "img/avatar.jpg"
      links = [
        { github = "https://github.com/jagudelol" },
        { orcid = "https://orcid.org/0009-0001-9147-0061" },
        { linkedin = "https://www.linkedin.com/in/joseagudelol-filosofo/" },
        { email = "mailto:tu@correo.com" },
        
      ]

[en]
  languageCode = "en"
  weight = 2
  languageName = "English"
  title = "Jose Agudelo"

  [en.params]
    description = "Philosopher, digital humanist, data scientist."

    [en.params.author]
      name = "Jose Agudelo Londoño"
      bio = "Digital humanist. Philosopher, communicator, and data scientist in training."
      headline = "Digital humanist. Philosopher, communicator, and data scientist in training."
      image = "img/avatar.jpg"
      links = [
        { github = "https://github.com/jagudelol" },
        { orcid = "https://orcid.org/0009-0001-9147-0061" },
        { linkedin = "https://www.linkedin.com/in/joseagudelol-filosofo/" },
        { email = "mailto:tu@correo.com" },
        
      ]
