[[main]]
  name = "Research"
  url = "/en/research/"
  weight = 10

[[main]]
  name = "CV"
  url = "/en/cv/"
  weight = 20

[[main]]
  name = "Contact"
  url = "/en/contact/"
  weight = 30

[[main]]
  name = ""
  weight = 80
  [main.params]
    action = "locale"

[[main]]
  name = ""
  weight = 90
  [main.params]
    action = "appearance"
