[[main]]
  name = "¿Quién soy?"
  url = "/about/"
  weight = 10
  
[[main]]
  name = "Investigación"
  url = "/investigacion/"
  weight = 20

[[main]]
  name = "Docencia"
  url = "/docencia/"
  weight = 30
  
[[main]]
  name = "Comunicación"
  url = "/comunicacion/"
  weight = 40

[[main]]
  name = "HD"
  url = "/hd/"
  weight = 50

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 60

[[main]]
  name = "Contacto"
  url = "/contact/"
  weight = 70

[[main]]
  name = ""
  weight = 80
  [main.params]
    action = "locale"

[[main]]
  name = ""
  weight = 90
  [main.params]
    action = "appearance"

[[main]]
  name = "RSS"
  url = "/index.xml"
  weight = 95
  [main.params]
    icon = "rss"
    showName = false

[[footer]]
  name = "Ahora"
  url = "/now/"
  weight = 10

[[footer]]
  name = "Stack"
  url = "/stack/"
  weight = 20
